# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='owner',
            new_name='parent',
        ),
    ]
